import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Navbar } from '@/components/user/Navbar';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Upload, Image as ImageIcon } from 'lucide-react';
import { toast } from 'sonner';
import axios from 'axios';

const AddBlog = () => {
  const navigate = useNavigate();
  const [title, setTitle] = useState('');
  const [category, setCategory] = useState('');
  const [content, setContent] = useState('');
  const [image, setImage] = useState(null);
  const [imagePreview, setImagePreview] = useState('');
  const [categories, setCategories] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);

  const currentUser = JSON.parse(localStorage.getItem('currentUser') || '{}');

  useEffect(() => {
    const fetchCategories = async () => {
      try {
        const res = await axios.get('http://localhost:5000/api/users/admin-categories');
        setCategories(res.data.map(c => ({ id: c.categoryID, name: c.categoryName })));
      } catch (err) {
        toast.error('Failed to load categories');
      } finally {
        setLoading(false);
      }
    };
    fetchCategories();
  }, []);

  const handleImageChange = (e) => {
    const file = e.target.files?.[0];
    if (file) {
      setImage(file);
      const reader = new FileReader();
      reader.onloadend = () => setImagePreview(reader.result);
      reader.readAsDataURL(file);
    }
  };

  const handleGenerateWithAI = async () => {
    if (!title.trim()) {
      toast.error('Please enter a blog title first');
      return;
    }
    if (!category) {
      toast.error('Please select a category');
      return;
    }

    setGenerating(true);
    toast.loading('AI is writing your blog...', { duration: 0 });

    try {
      const response = await fetch(
        `https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash:generateContent?key=${import.meta.env.VITE_GEMINI_API_KEY}`,
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            contents: [{
              parts: [{
                text: `You are an expert blogger and technical writer. Write a detailed, engaging blog post in English (500-1000 words only).

Title: "${title}"
Category: ${categories.find(c => c.id.toString() === category)?.name || 'General'}

Instructions:
- If the title asks for code (like "write HTML code", "create a form", "CSS", "JavaScript", etc.), then provide the complete, properly indented, and formatted code inside a code block.
- Use triple backticks with language name for code blocks (e.g., \`\`\`html, \`\`\`css, \`\`\`javascript).
- Make sure code has proper indentation (2 or 4 spaces), correct syntax, and is easy to copy-paste.
- Explain the code step-by-step in the blog content.
- For non-code topics, write naturally with good paragraphs, headings if needed, and engaging language.

Rules:
- Do NOT include the title or category name in the content.
- Start directly with the first paragraph or code block.
- Use proper formatting: bold, italics, lists when appropriate.
- Always end with a meaningful conclusion.
- Keep total length between 500-1000 words.
`
              }]
            }]
          })
        }
      );

      if (!response.ok) {
        throw new Error(`HTTP ${response.status}`);
      }

      const data = await response.json();

      if (!data.candidates?.[0]?.content?.parts?.[0]?.text) {
        throw new Error('No content generated by AI');
      }

      const generatedText = data.candidates[0].content.parts[0].text;

      setContent(generatedText.trim());
      toast.dismiss();
      toast.success('AI generated your blog! You can edit it now');
    } catch (err) {
      toast.dismiss();
      toast.error('AI generation failed. Please try again!');
      console.error('Gemini Error:', err);
    } finally {
      setGenerating(false);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!currentUser.userID) {
      toast.error('Please login');
      return;
    }
    if (!title.trim() || title.trim().length < 5 || title.trim().length > 100) {
      toast.error('Title must be 5–100 characters');
      return;
    }
    if (!content.trim() || content.trim().length < 100) {
      toast.error('Content must be at least 100 characters');
      return;
    }
    if (!category) {
      toast.error('Please select a category');
      return;
    }
    if (!image) {
      toast.error('Image is required');
      return;
    }

    const formData = new FormData();
    formData.append('blogTitle', title.trim());
    formData.append('blogDescription', content.trim());
    formData.append('categoryID', category);
    formData.append('blogImage', image);

    try {
      await axios.post(
        'http://localhost:5000/api/users/blogs',
        formData,
        { withCredentials: true }
      );
      toast.success('Blog submitted for approval!');
      setTimeout(() => navigate('/blogs'), 1500);
    } catch (err) {
      toast.error(err.response?.data?.msg || 'Failed to submit');
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      <Navbar />

      <main className="container mx-auto px-4 py-8 max-w-3xl">
        <div className="mb-8 animate-fade-in">
          <h1 className="text-4xl font-bold mb-2">Create New Blog</h1>
          <p className="text-muted-foreground">Share your story with the world</p>
        </div>

        <Card className="animate-fade-in-up">
          <CardHeader>
            <CardTitle>Blog Details</CardTitle>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleSubmit} className="space-y-6">
              <div className="space-y-2">
                <Label htmlFor="title">Title *</Label>
                <Input
                  id="title"
                  placeholder="Enter your blog title (5–100 chars)"
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="category">Category *</Label>
                <Select value={category} onValueChange={setCategory}>
                  <SelectTrigger>
                    <SelectValue placeholder="Select a category" />
                  </SelectTrigger>
                  <SelectContent>
                    {categories.map(cat => (
                      <SelectItem key={cat.id} value={cat.id.toString()}>
                        {cat.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-2">
                <Label htmlFor="image">Featured Image *</Label>
                <div className="border-2 border-dashed rounded-lg p-8 text-center hover:border-primary transition-colors">
                  {imagePreview ? (
                    <div className="space-y-4">
                      <img src={imagePreview} alt="Preview" className="max-h-64 mx-auto rounded-lg" />
                      <Button type="button" variant="outline" onClick={() => { setImage(null); setImagePreview(''); }}>
                        Change Image
                      </Button>
                    </div>
                  ) : (
                    <label htmlFor="image" className="cursor-pointer block">
                      <ImageIcon className="h-12 w-12 mx-auto mb-4 text-muted-foreground" />
                      <p className="text-muted-foreground mb-2">Click to upload</p>
                      <p className="text-xs text-muted-foreground">PNG, JPG, WEBP (max 5MB)</p>
                      <input
                        id="image"
                        type="file"
                        accept="image/*"
                        className="hidden"
                        onChange={handleImageChange}
                        required
                      />
                    </label>
                  )}
                </div>
              </div>

              <div className="space-y-2">
                <Label htmlFor="content">Content * (min 100 chars)</Label>
                <Textarea
                  id="content"
                  placeholder="Write your blog content here..."
                  value={content}
                  onChange={(e) => setContent(e.target.value)}
                  className="min-h-[300px] resize-none"
                />
                <p className="text-xs text-muted-foreground text-right">
                  {content.length} / 100+ characters
                </p>
                {generating && (
                  <p className="text-sm text-primary animate-pulse text-center mt-4">
                    AI is crafting your masterpiece...
                  </p>
                )}
              </div>

              <div className="flex flex-wrap gap-3 justify-end">
                <Button type="button" variant="outline" onClick={() => navigate('/blogs')}>
                  Cancel
                </Button>

                <Button
                  type="button"
                  variant="secondary"
                  onClick={handleGenerateWithAI}
                  disabled={generating || !title.trim() || !category}
                  className="gap-2"
                >
                  {generating ? (
                    <>Generating...</>
                  ) : (
                    <>
                      Generate with AI
                    </>
                  )}
                </Button>

                <Button type="submit" className="gap-2" disabled={generating}>
                  <Upload className="h-4 w-4" />
                  Submit for Approval
                </Button>
              </div>

            </form>
          </CardContent>
        </Card>
      </main>
    </div>
  );
};

export default AddBlog;