export const mockUsers = [
  {
    id: '1',
    username: 'John Doe',
    email: 'john@example.com',
    profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    joinedDate: '2024-01-15',
    role: 'user',
  },
  {
    id: '2',
    username: 'Jane Smith',
    email: 'jane@example.com',
    profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    joinedDate: '2024-02-20',
    role: 'user',
  },
  {
    id: 'admin',
    username: 'Admin User',
    email: 'admin@example.com',
    profilePicture: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Admin',
    joinedDate: '2024-01-01',
    role: 'admin',
  },
];

export const mockBlogs = [
  {
    id: '1',
    title: 'Getting Started with React 19',
    image: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&h=400&fit=crop',
    category: 'Tech',
    content: 'React 19 brings exciting new features including improved server components, enhanced performance optimizations, and better developer experience. In this comprehensive guide, we will explore all the major changes and how to leverage them in your projects.',
    snippet: 'React 19 brings exciting new features including improved server components...',
    author: 'John Doe',
    authorId: '1',
    date: '2024-03-15',
    likes: 142,
    comments: [],
    featured: true,
  },
  {
    id: '2',
    title: 'Exploring the Hidden Gems of Japan',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&h=400&fit=crop',
    category: 'Travel',
    content: 'Join me on a journey through Japan\'s lesser-known destinations. From tranquil mountain villages to serene coastal towns, discover the authentic beauty of Japan beyond the typical tourist spots.',
    snippet: 'Join me on a journey through Japan\'s lesser-known destinations...',
    author: 'Jane Smith',
    authorId: '2',
    date: '2024-03-14',
    likes: 98,
    comments: [],
    featured: true,
  },
  {
    id: '3',
    title: 'The Art of Minimalist Cooking',
    image: 'https://images.unsplash.com/photo-1495521821757-a1efb6729352?w=800&h=400&fit=crop',
    category: 'Food',
    content: 'Discover how minimalist cooking can transform your relationship with food. Learn to create delicious meals with fewer ingredients, less waste, and more mindfulness.',
    snippet: 'Discover how minimalist cooking can transform your relationship with food...',
    author: 'John Doe',
    authorId: '1',
    date: '2024-03-13',
    likes: 76,
    comments: [],
    featured: true,
  },
  {
    id: '4',
    title: 'Building Better Habits in 2024',
    image: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800&h=400&fit=crop',
    category: 'Lifestyle',
    content: 'Transform your life with science-backed strategies for habit formation. This guide covers everything from morning routines to evening rituals that stick.',
    snippet: 'Transform your life with science-backed strategies for habit formation...',
    author: 'Jane Smith',
    authorId: '2',
    date: '2024-03-12',
    likes: 134,
    comments: [],
    featured: true,
  },
  {
    id: '5',
    title: 'Understanding TypeScript Generics',
    image: 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=800&h=400&fit=crop',
    category: 'Tech',
    content: 'Master TypeScript generics with practical examples and real-world use cases. Learn how to write more flexible and reusable code.',
    snippet: 'Master TypeScript generics with practical examples and real-world use cases...',
    author: 'John Doe',
    authorId: '1',
    date: '2024-03-11',
    likes: 89,
    comments: [],
    featured: false,
  },
  {
    id: '6',
    title: 'Sustainable Travel Tips for 2024',
    image: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&h=400&fit=crop',
    category: 'Travel',
    content: 'Learn how to travel responsibly while minimizing your environmental impact. Practical tips for eco-conscious adventurers.',
    snippet: 'Learn how to travel responsibly while minimizing your environmental impact...',
    author: 'Jane Smith',
    authorId: '2',
    date: '2024-03-10',
    likes: 112,
    comments: [],
    featured: false,
  },
];

export const categories = ['All', 'Tech', 'Travel', 'Food', 'Lifestyle'];
